spring:
  application:
    name: movieflix

  datasource:
    url: jdbc:postgresql://localhost:5432/movieflix
    username: postgres
    password: uhtred
    driver-class-name: org.postgresql.Driver

    jpa:
    database-platform: org.hibernate.dialect.PostgresSQLDialect
    show-sql: true

    flyway:
      enabled: true